In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
x = np.linspace(0,4*np.pi,60000)
X = []
for i in range(len(x)):
    X.append([x[i]])
X[7500]

[1.5708225071700161]

In [4]:
Y = np.sin(x)
y = []
for i in range(len(Y)):
    y.append([Y[i]])


In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
sc = StandardScaler()

In [7]:
X = sc.fit_transform(X)
X

array([[-1.73202194],
       [-1.73196421],
       [-1.73190647],
       ...,
       [ 1.73190647],
       [ 1.73196421],
       [ 1.73202194]])

In [8]:
y = sc.transform(y)
y

array([[-1.73202194],
       [-1.73196421],
       [-1.73190647],
       ...,
       [-1.73213741],
       [-1.73207968],
       [-1.73202194]])

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [11]:
len(y_train)

48000

In [12]:
len(y_test)

12000

In [13]:
ann = tf.keras.models.Sequential()

In [14]:
ann.add(tf.keras.layers.Dense(units=6,activation='sigmoid'))

In [15]:
ann.add(tf.keras.layers.Dense(units=6,activation='sigmoid'))

In [16]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [17]:
ann.compile(optimizer = 'adam' , loss = 'mean_squared_error' , metrics = ['mean_squared_error'])

In [18]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
1500/1500 [==============================] - 2s 952us/step - loss: 3.2875 - mean_squared_error: 3.2875
Epoch 2/100
1500/1500 [==============================] - 1s 924us/step - loss: 3.0546 - mean_squared_error: 3.0546
Epoch 3/100
1500/1500 [==============================] - 1s 906us/step - loss: 3.0439 - mean_squared_error: 3.0439
Epoch 4/100
1500/1500 [==============================] - 1s 955us/step - loss: 3.0408 - mean_squared_error: 3.04080s - loss: 3.0378 - mean_squared_err - ETA: 0s - loss: 3.0391 - mean_squared_err
Epoch 5/100
1500/1500 [==============================] - ETA: 0s - loss: 3.0406 - mean_squared_error: 3.04 - 1s 944us/step - loss: 3.0397 - mean_squared_error: 3.0397
Epoch 6/100
1500/1500 [==============================] - 1s 927us/step - loss: 3.0393 - mean_squared_error: 3.0393
Epoch 7/100
1500/1500 [==============================] - 1s 943us/step - loss: 3.0391 - mean_squared_error: 3.0391
Epoch 8/100
1500/1500 [==============================] - 1s 968

In [22]:
o = [0.00001]
o

[1e-05]

In [23]:
o = sc.transform([o]) 
o

array([[-1.73201918]])

In [24]:
ann.predict(o)

array([[4.0592307e-11]], dtype=float32)